import { Router } from "express";
import { authenticate, requireRoles } from "./modules/auth/auth.middleware.js";
import { authRouter } from "./modules/auth/auth.routes.js";
import { dashboardRouter } from "./modules/dashboard/dashboard.routes.js";
import { departmentsRouter } from "./modules/departments/departments.routes.js";
import { employeesRouter } from "./modules/employees/employees.routes.js";
import { attendanceRouter } from "./modules/attendance/attendance.routes.js";
import { shiftsRouter } from "./modules/shifts/shifts.routes.js";
import { schedulesRouter } from "./modules/schedules/schedules.routes.js";
import { payrollRouter } from "./modules/payroll/payroll.routes.js";
import { leavesRouter } from "./modules/leaves/leaves.routes.js";
import { notificationsRouter } from "./modules/notifications/notifications.routes.js";
import { settingsRouter } from "./modules/settings/settings.routes.js";
import { reportsRouter } from "./modules/reports/reports.routes.js";
import { aiRouter } from "./modules/ai/ai.routes.js";
import { tenantsRouter } from "./modules/tenants/tenants.routes.js";
import { kpisRouter } from "./modules/kpis/kpis.routes.js";
import { profileRouter } from "./modules/profile/profile.routes.js";
import { communityRouter } from "./modules/community/community.routes.js";

export const apiRouter = Router();

apiRouter.use("/auth", authRouter);
apiRouter.use("/tenants", tenantsRouter);
apiRouter.use("/profile", authenticate, requireRoles("Admin", "Employee"), profileRouter);
apiRouter.use("/community", authenticate, requireRoles("Admin", "Employee"), communityRouter);
apiRouter.use("/dashboard", authenticate, requireRoles("Admin"), dashboardRouter);
apiRouter.use("/departments", authenticate, requireRoles("Admin"), departmentsRouter);
apiRouter.use("/employees", authenticate, employeesRouter);
apiRouter.use("/attendance", authenticate, attendanceRouter);
apiRouter.use("/shifts", authenticate, shiftsRouter);
apiRouter.use("/schedules", authenticate, schedulesRouter);
apiRouter.use("/payroll", authenticate, requireRoles("Admin", "Employee"), payrollRouter);
apiRouter.use("/leaves", authenticate, leavesRouter);
apiRouter.use("/notifications", authenticate, notificationsRouter);
apiRouter.use("/settings", authenticate, requireRoles("Admin"), settingsRouter);
apiRouter.use("/reports", authenticate, requireRoles("Admin"), reportsRouter);
apiRouter.use("/ai", authenticate, requireRoles("Admin"), aiRouter);
apiRouter.use("/kpis", authenticate, requireRoles("Admin", "Employee"), kpisRouter);
