import { apiClient } from "./client";

export const bizenApi = {
  passwordLogin: (payload) => apiClient.post("/auth/login", payload),
  googleLogin: (credential) => apiClient.post("/auth/google", { credential }),
  me: () => apiClient.get("/auth/me"),
  createCompanyRequest: (payload) => apiClient.post("/tenants/company-requests", payload),
  companyRequests: (status = "Pending") => apiClient.get(`/tenants/company-requests?status=${encodeURIComponent(status)}`),
  reviewCompanyRequest: (id, payload) => apiClient.patch(`/tenants/company-requests/${id}/status`, payload),
  requestEmployeeAccount: (payload) => apiClient.post("/auth/employee-account-requests", payload),
  accountRequests: (status = "Pending") => apiClient.get(`/auth/account-requests?status=${encodeURIComponent(status)}`),
  reviewAccountRequest: (id, payload) => apiClient.patch(`/auth/account-requests/${id}/status`, payload),
  dashboardSummary: () => apiClient.get("/dashboard/summary"),
  dashboardCharts: () => apiClient.get("/dashboard/charts"),
  departments: () => apiClient.get("/departments"),
  employees: () => apiClient.get("/employees"),
  employee: (id) => apiClient.get(`/employees/${id}`),
  createEmployee: (payload) => apiClient.post("/employees", payload),
  updateEmployee: (id, payload) => apiClient.patch(`/employees/${id}`, payload),
  deleteEmployee: (id) => apiClient.delete(`/employees/${id}`),
  attendance: (date) => apiClient.get(`/attendance${date ? `?date=${encodeURIComponent(date)}` : ""}`),
  employeeAttendance: (employeeId) => apiClient.get(`/attendance/employee/${employeeId}`),
  upsertAttendance: (payload) => apiClient.post("/attendance", payload),
  faceEnroll: (payload) => apiClient.post("/attendance/face-enroll", payload),
  faceCheckin: (payload) => apiClient.post("/attendance/face-checkin", payload),
  faceEnrollments: (status = "All") => apiClient.get(`/attendance/face-enrollments?status=${encodeURIComponent(status)}`),
  faceEnrollmentStatus: (employeeId) => apiClient.get(`/attendance/face-enrollments/employee/${employeeId}/latest`),
  reviewFaceEnrollment: (id, payload) => apiClient.patch(`/attendance/face-enrollments/${id}/status`, payload),
  faceEnrollmentImage: (id) => apiClient.blob(`/attendance/face-enrollments/${id}/image`),
  shifts: () => apiClient.get("/shifts"),
  scheduleWeek: () => apiClient.get("/schedules/week"),
  updateScheduleWeek: (payload) => apiClient.put("/schedules/week", payload),
  aiSuggestSchedule: () => apiClient.post("/schedules/ai-suggest", {}),
  payroll: (month = "05/2026") => apiClient.get(`/payroll?month=${encodeURIComponent(month)}`),
  calculatePayroll: (month = "05/2026") => apiClient.post("/payroll/calculate", { month }),
  payrollDetail: (employeeId, month = "05/2026") => apiClient.get(`/payroll/${employeeId}?month=${encodeURIComponent(month)}`),
  leaves: () => apiClient.get("/leaves"),
  createLeave: (payload) => apiClient.post("/leaves", payload),
  updateLeaveStatus: (id, status) => apiClient.patch(`/leaves/${id}/status`, { status }),
  notifications: (employeeId) => apiClient.get(`/notifications${employeeId ? `?employeeId=${encodeURIComponent(employeeId)}` : ""}`),
  settings: () => apiClient.get("/settings"),
  updateSettings: (payload) => apiClient.put("/settings", payload),
  reports: () => apiClient.get("/reports"),
  aiAlerts: () => apiClient.get("/ai/alerts"),
  aiChat: (message) => apiClient.post("/ai/chat", { message })
};
